### ISSUE TITLE
changes don't stay active.

### ISSUE THREAD

**Issue by nathgit** [dsivasuthan/change-all-ui-fonts#1]
When I type in a font name it briefly switches to the new font, then in a few seconds switches back. I just installed it on updated chrome os.

**Comment by dsivasuthan** [comment]
Does the change persist when you refresh the page. Changes take effect only when you refresh the page after clicking Save. I hope that helps.

**Comment by nathgit** [comment]
Maybe It's just not clear to me how it's supposed to work, because now it's not even changing at all even after a refresh. Is there some reason it wouldn't work on a chromebook?

**Comment by nathgit** [comment]
To answer you're original question, no it doesn't. That's the problem.

**Comment by sirius707** [comment]
> To answer you're original question, no it doesn't. That's the problem.

did you make sure to check that the extension has permission to work on all websites? 

it's working fine for me.

**Comment by dsivasuthan** [comment]
> To answer you're original question, no it doesn't. That's the problem.

It might be too late for this issue but only server-rendered work properly with this application. Single Page Applications (made with Vue, Angular) usually don't work well as they have inline styles that are dynamic, Thanks.

**Comment by dsivasuthan** [comment]
I am closing the issue as there are no response.
