### ISSUE TITLE
apply local fonts?

### ISSUE THREAD

**Issue by nathgit** [dsivasuthan/change-all-ui-fonts#2]
How do I apply 'local' fonts as the chrome webstore page says you can do? That's the only reason I installed this. I don't see any option to configure anything.

**Comment by dsivasuthan** [comment]
You can only choose local fonts. After installation, click on the extension icon, and enter the name of the font you want to use and Click save, and refresh the page. That's all. Make sure you enter the name exactly as it appears on something like MS Word or Notepad. Thanks
