### ISSUE TITLE
confusion on how this works

### ISSUE THREAD

**Issue by skittleskitsune** [dsivasuthan/change-all-ui-fonts#4]
hi, sorry if this isn't the right place for this (i haven't used github before and i didnt see anywhere for comments) but im wondering how this works exactly?

i'm trying to change my browser's font to Determination Sans - the undertale font - and it's installed on my pc and everything

if i input the filename, or the font name, into the little font input, neither works. how does one use this? thanks :3c

**Comment by dsivasuthan** [comment]
If you install via Chrome Web Store, you can just copy paste the font name and hit Save. You should refresh the page, and it should work. It wouldn't work on special Chrome pages like chrome://...

**Comment by skittleskitsune** [comment]
but how do i.. get the font name?
