### ISSUE TITLE
it wont work

### ISSUE THREAD

**Issue by deltakr1s** [dsivasuthan/change-all-ui-fonts#5]
i type in VCR OSD Mono (the font i want to use) i have it installed on my pc but it still wont work. i use Opera GX. i try everything but still no luck

**Comment by dsivasuthan** [comment]
Did you restart browser? This extension is made for Chrome. I just tried the font you mentioned on Chrome and it worked.

![image](https://github.com/dsivasuthan/change-all-ui-fonts/assets/1507367/eab38dc3-ae8f-4907-8096-e54b7f79313c)
